<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 - Página não encontrada</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/public/css/error.css">
</head>

<body>

    <div class="error-container">
        <div class="error-code">404</div>
        <div class="error-message">Página não encontrada</div>
        <button class="btn btn-primary" onclick="window.history.back()">Voltar</button>
    </div>

</body>

</html>